# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee1bef223ef09657195e370229ab0087159613ec47266ec1fc697733662badedb6b0315860698f5d0f7e315006a92b566b225cf29b3190b45ee4526f069eb95

test:
  secret_key_base: eb0311aae2b2a2c88f407a06a505f660caa05b8e0ce1640af4d91ba56e418822b2142ed15e7562308fe569aab05a5d580ebb715668c6fef736ea5a34848bf1ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
